eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10087/eureka/
server:
  port: 11086
spring:
  application:
    name: eurekaclient
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest

